name: Lint and unit tests
on:
  push:
    branches:
      - "**"
    tags:
      - "v*"
  pull_request:
    branches:
      - master
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@master
        with:
          go-version: "1.21"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.54
          # caching issues, see: https://github.com/golangci/golangci-lint-action/issues/244#issuecomment-1052190775
          skip-pkg-cache: true
          skip-build-cache: true
          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Check out code
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Setup Go
        uses: actions/setup-go@master
        with:
          go-version: 1.21
      - run: |
          GOPROXY=direct,https://proxy.golang.org GOSUMDB=off GO111MODULE=on go test -v ./...
